# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from ably_platform_python_sdk.paths.channels_channel_id_messages.get import GetMessagesByChannelRaw
from ably_platform_python_sdk.paths.channels_channel_id_presence_history.get import GetPresenceHistoryOfChannelRaw


class HistoryApiRaw(
    GetMessagesByChannelRaw,
    GetPresenceHistoryOfChannelRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
