# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from ably_platform_python_sdk.paths.push_channel_subscriptions.delete import DeletePushDeviceDetailsRaw
from ably_platform_python_sdk.paths.push_channels.get import GetChannelsWithPushSubscribersRaw
from ably_platform_python_sdk.paths.push_device_registrations_device_id.get import GetPushDeviceDetailsRaw
from ably_platform_python_sdk.paths.push_channel_subscriptions.get import GetPushSubscriptionsOnChannelsRaw
from ably_platform_python_sdk.paths.push_device_registrations.get import GetRegisteredPushDevicesRaw
from ably_platform_python_sdk.paths.push_device_registrations_device_id.patch import PatchPushDeviceDetailsRaw
from ably_platform_python_sdk.paths.push_publish.post import PublishPushNotificationToDevicesRaw
from ably_platform_python_sdk.paths.push_device_registrations_device_id.put import PutPushDeviceDetailsRaw
from ably_platform_python_sdk.paths.push_device_registrations.post import RegisterPushDeviceRaw
from ably_platform_python_sdk.paths.push_channel_subscriptions.post import SubscribePushDeviceToChannelRaw
from ably_platform_python_sdk.paths.push_device_registrations.delete import UnregisterAllPushDevicesRaw
from ably_platform_python_sdk.paths.push_device_registrations_device_id.delete import UnregisterPushDeviceRaw
from ably_platform_python_sdk.paths.push_device_registrations_device_id_reset_update_token.get import UpdatePushDeviceDetailsRaw


class PushApiRaw(
    DeletePushDeviceDetailsRaw,
    GetChannelsWithPushSubscribersRaw,
    GetPushDeviceDetailsRaw,
    GetPushSubscriptionsOnChannelsRaw,
    GetRegisteredPushDevicesRaw,
    PatchPushDeviceDetailsRaw,
    PublishPushNotificationToDevicesRaw,
    PutPushDeviceDetailsRaw,
    RegisterPushDeviceRaw,
    SubscribePushDeviceToChannelRaw,
    UnregisterAllPushDevicesRaw,
    UnregisterPushDeviceRaw,
    UpdatePushDeviceDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
