# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from ably_platform_python_sdk.paths.channels.get import GetMetadataOfAllChannels
from ably_platform_python_sdk.paths.channels_channel_id.get import GetMetadataOfChannel
from ably_platform_python_sdk.paths.channels_channel_id_presence.get import GetPresenceOfChannel
from ably_platform_python_sdk.apis.tags.status_api_raw import StatusApiRaw


class StatusApi(
    GetMetadataOfAllChannels,
    GetMetadataOfChannel,
    GetPresenceOfChannel,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StatusApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StatusApiRaw(api_client)
