# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ably_platform_python_sdk import schemas  # noqa: F401


class ChannelDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "channelId",
        }
        
        class properties:
            channelId = schemas.StrSchema
            isGlobalMaster = schemas.BoolSchema
            region = schemas.StrSchema
        
            @staticmethod
            def status() -> typing.Type['ChannelStatus']:
                return ChannelStatus
            __annotations__ = {
                "channelId": channelId,
                "isGlobalMaster": isGlobalMaster,
                "region": region,
                "status": status,
            }
    
    channelId: MetaOapg.properties.channelId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channelId"]) -> MetaOapg.properties.channelId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isGlobalMaster"]) -> MetaOapg.properties.isGlobalMaster: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'ChannelStatus': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["channelId", "isGlobalMaster", "region", "status", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channelId"]) -> MetaOapg.properties.channelId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isGlobalMaster"]) -> typing.Union[MetaOapg.properties.isGlobalMaster, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> typing.Union[MetaOapg.properties.region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union['ChannelStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["channelId", "isGlobalMaster", "region", "status", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        channelId: typing.Union[MetaOapg.properties.channelId, str, ],
        isGlobalMaster: typing.Union[MetaOapg.properties.isGlobalMaster, bool, schemas.Unset] = schemas.unset,
        region: typing.Union[MetaOapg.properties.region, str, schemas.Unset] = schemas.unset,
        status: typing.Union['ChannelStatus', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ChannelDetails':
        return super().__new__(
            cls,
            *args,
            channelId=channelId,
            isGlobalMaster=isGlobalMaster,
            region=region,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )

from ably_platform_python_sdk.model.channel_status import ChannelStatus
