# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ably_platform_python_sdk import schemas  # noqa: F401


class Push(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def apns() -> typing.Type['PushApns']:
                return PushApns
            data = schemas.StrSchema
        
            @staticmethod
            def fcm() -> typing.Type['PushFcm']:
                return PushFcm
        
            @staticmethod
            def notification() -> typing.Type['Notification']:
                return Notification
        
            @staticmethod
            def web() -> typing.Type['PushWeb']:
                return PushWeb
            __annotations__ = {
                "apns": apns,
                "data": data,
                "fcm": fcm,
                "notification": notification,
                "web": web,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apns"]) -> 'PushApns': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["data"]) -> MetaOapg.properties.data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fcm"]) -> 'PushFcm': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notification"]) -> 'Notification': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["web"]) -> 'PushWeb': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["apns", "data", "fcm", "notification", "web", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apns"]) -> typing.Union['PushApns', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["data"]) -> typing.Union[MetaOapg.properties.data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fcm"]) -> typing.Union['PushFcm', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notification"]) -> typing.Union['Notification', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["web"]) -> typing.Union['PushWeb', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["apns", "data", "fcm", "notification", "web", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        apns: typing.Union['PushApns', schemas.Unset] = schemas.unset,
        data: typing.Union[MetaOapg.properties.data, str, schemas.Unset] = schemas.unset,
        fcm: typing.Union['PushFcm', schemas.Unset] = schemas.unset,
        notification: typing.Union['Notification', schemas.Unset] = schemas.unset,
        web: typing.Union['PushWeb', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Push':
        return super().__new__(
            cls,
            *args,
            apns=apns,
            data=data,
            fcm=fcm,
            notification=notification,
            web=web,
            _configuration=_configuration,
            **kwargs,
        )

from ably_platform_python_sdk.model.notification import Notification
from ably_platform_python_sdk.model.push_apns import PushApns
from ably_platform_python_sdk.model.push_fcm import PushFcm
from ably_platform_python_sdk.model.push_web import PushWeb
