# coding: utf-8

"""
    Platform API

    The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.

    The version of the OpenAPI document: 1.1.0
    Contact: support@ably.io
    Created by: https://www.ably.io/contact
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ably_platform_python_sdk import schemas  # noqa: F401


class TokenRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "capability",
            "keyName",
            "nonce",
            "timestamp",
        }
        
        class properties:
            capability = schemas.DictSchema
            keyName = schemas.StrSchema
            nonce = schemas.StrSchema
            timestamp = schemas.IntSchema
            clientId = schemas.StrSchema
            __annotations__ = {
                "capability": capability,
                "keyName": keyName,
                "nonce": nonce,
                "timestamp": timestamp,
                "clientId": clientId,
            }
    
    capability: MetaOapg.properties.capability
    keyName: MetaOapg.properties.keyName
    nonce: MetaOapg.properties.nonce
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["capability"]) -> MetaOapg.properties.capability: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["keyName"]) -> MetaOapg.properties.keyName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nonce"]) -> MetaOapg.properties.nonce: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientId"]) -> MetaOapg.properties.clientId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["capability", "keyName", "nonce", "timestamp", "clientId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["capability"]) -> MetaOapg.properties.capability: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["keyName"]) -> MetaOapg.properties.keyName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nonce"]) -> MetaOapg.properties.nonce: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientId"]) -> typing.Union[MetaOapg.properties.clientId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["capability", "keyName", "nonce", "timestamp", "clientId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        capability: typing.Union[MetaOapg.properties.capability, dict, frozendict.frozendict, ],
        keyName: typing.Union[MetaOapg.properties.keyName, str, ],
        nonce: typing.Union[MetaOapg.properties.nonce, str, ],
        timestamp: typing.Union[MetaOapg.properties.timestamp, decimal.Decimal, int, ],
        clientId: typing.Union[MetaOapg.properties.clientId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TokenRequest':
        return super().__new__(
            cls,
            *args,
            capability=capability,
            keyName=keyName,
            nonce=nonce,
            timestamp=timestamp,
            clientId=clientId,
            _configuration=_configuration,
            **kwargs,
        )
